CREATE TABLE CAD_OPERACAO (
CD_OPERACAO INTEGER NOT NULL,
DS_OPERACAO VARCHAR(40),
TP_OPERACAO CHAR(1),
CONSTRAINT PK_OPERACAO PRIMARY KEY(CD_OPERACAO)
);

CREATE TABLE CAD_PESSOA (
CD_PESSOA INTEGER NOT NULL,
DS_PESSOA VARCHAR(60),
CONSTRAINT PK_PESSOA PRIMARY KEY (CD_PESSOA)
);

CREATE TABLE CAD_ITENS (
CD_ITEM INTEGER NOT NULL,
DS_ITEM VARCHAR(40),
VL_ITEM NUMBER(9,2),
QT_ESTOQUE INTEGER,
CONSTRAINT PK_ITENS PRIMARY KEY (CD_ITEM)
);

CREATE TABLE CAD_FORMA_PG (
CD_FORMA INTEGER NOT NULL,
DS_FORMA VARCHAR(40),
NR_PARCELAS INTEGER,
IN_ENTRADA CHAR(1),
NR_INTERVALO INTEGER,
CONSTRAINT PK_FORMA_PG PRIMARY KEY (CD_FORMA)
);

CREATE TABLE MOV_NF(
CD_NF INTEGER NOT NULL,
SR_NF CHAR(10) NOT NULL,
CD_PESSOA INTEGER NOT NULL,
DT_NF DATE,
CD_OPERACAO INTEGER NOT NULL,
CD_FORMA INTEGER NOT NULL,
CONSTRAINT PK_MOV_NF PRIMARY KEY (CD_NF, SR_NF),
CONSTRAINT FK_PESSOA FOREIGN KEY (CD_PESSOA) REFERENCES CAD_PESSOA(CD_PESSOA)
);

CREATE TABLE MOV_PARCELAS (
CD_NF INTEGER NOT NULL,
NR_PARCELA INTEGER NOT NULL,
CD_PESSOA INTEGER NOT NULL,
SR_NF CHAR(10) NOT NULL,
DT_PAGO DATE,
DT_PAGAMENTO DATE,
VL_PAGO NUMBER(9,2),
VL_PAGAMENTO NUMBER(9,2),
CONSTRAINT PK_MOV_PARCELAS PRIMARY KEY (CD_NF,SR_NF, NR_PARCELA),
CONSTRAINT FK_NF FOREIGN KEY (CD_NF, SR_NF) REFERENCES MOV_NF(CD_NF, SR_NF)
);

CREATE TABLE MOV_NF_ITEM (
CD_ITEM INTEGER NOT NULL,
SR_NF CHAR(10) NOT NULL,
CD_NF INTEGER NOT NULL,
CD_PESSOA INTEGER NOT NULL,
VL_ITEM NUMBER(9,2),
QT_ITEM NUMBER(9,2),
CONSTRAINT PK_MOV_NF_ITEM PRIMARY KEY (CD_ITEM, CD_NF, SR_NF),
CONSTRAINT FK_ITENS FOREIGN KEY (CD_ITEM) REFERENCES CAD_ITENS(CD_ITEM),
CONSTRAINT FK_M_NF FOREIGN KEY (CD_NF, SR_NF) REFERENCES MOV_NF(CD_NF, SR_NF));



--CAD_OPERACAO criado.
--CAD_PESSOA criado.
--CAD_ITENS criado.
--CAD_FORMA_PG criado.
--MOV_NF criado.
--MOV_PARCELAS criado.
--MOV_NF_ITEM criado.